name: Publish Any Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Echo process env
        run: echo process.env

      - name: Install dependencies
        run: npm install

      - run: npx pkg-pr-new publish
